// src/components/ui/greeting/Greeting.tsx
import React, { useState, useEffect } from 'react'

export default function Greeting() {
  const [greeting, setGreeting] = useState<string>('')

  let today = new Date()
  let curHr = today.getHours()

  useEffect(() => {
    if (curHr < 12) {
      setGreeting('morning')
    } else if (curHr < 18) {
      setGreeting('afternoon')
    } else {
      setGreeting('evening')
    }
  }, [curHr])

  return (
    <>
      <h1 className='text-4xl font-extrabold mb-4'>
        <span className='font-light'>Good</span>
        {' ' + greeting}
      </h1>
    </>
  )
}

// src/lib/components/greeting/Greeting.svelte
<script>
	import { onMount } from 'svelte';
	import { fade } from 'svelte/transition';
	let greeting = null;

	let today = new Date();
	let curHr = today.getHours();

	onMount(() => {
		if (curHr < 12) {
			greeting = 'morning';
		} else if (curHr < 18) {
			greeting = 'afternoon';
		} else {
			greeting = 'evening';
		}
	});
</script>

{#if greeting}
	<h1 in:fade={{ duration: 300 }} class="text-4xl font-extrabold mb-8">
		<span class="font-light">Good</span>
		{greeting}
	</h1>
{/if}
