// src/lib/components/ui/modals/Modal.svelte
<script>
	import { createEventDispatcher } from 'svelte';
	import { fade, fly } from 'svelte/transition';
	import { clickOutside } from 'svelte-use-click-outside';

	const dispatch = createEventDispatcher();
	export let open = false;
</script>

{#if open}
	<div
		transition:fade={{ duration: 300 }}
		class="overlay fixed top-0 left-0 z-30 bg-black/40 backdrop-blur-md h-screen w-screen"
	/>
	<div
		transition:fly={{ duration: 300, y: -100 }}
		use:clickOutside={() => dispatch('clickOutside')}
		class="fixed delete-modal p-6 z-40 bg-white shadow-2xl text-neutral-800 rounded-3xl top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"
	>
		<slot />
	</div>
{/if}

// src/components/ui/modal/Modal.tsx
import React from 'react'
import { animated, useSpring } from 'react-spring'
import { HiX } from 'react-icons/hi'

export default function Modal({
  open,
  children,
  handleClose,
  modalTitle,
}: {
  open: boolean
  children: React.ReactNode
  handleClose: React.MouseEventHandler
  modalTitle?: string
}) {
  const modalStyles = useSpring({
    opacity: open ? 1 : 0,
    y: open ? '-50%' : '0%',
    x: open ? '-50%' : '-50%',
  })

  const overlayStyles = useSpring({
    opacity: open ? 1 : 0,
  })
  return (
    <>
      {open && (
        <>
          <animated.div
            style={modalStyles}
            className='px-6 py-3 bg-white w-1/2 z-50 transform rounded-3xl fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2'
          >
            <div
              onClick={handleClose}
              className='absolute right-3 cursor-pointer hover:text-gray-800 top-3 close-button'
            >
              <HiX className='h-6 w-6 text-gray-600 hover:text-gray-800' />
            </div>
            {modalTitle && (
              <div className='modal-title'>
                <h2 className='text-2xl text-gray-500 tracking-tight font-light mb-4'>
                  {modalTitle}
                </h2>
              </div>
            )}
            {children}
          </animated.div>
          <animated.div
            onClick={handleClose}
            style={overlayStyles}
            className='fixed z-40 top-0 left-0 w-screen h-screen bg-black/40 backdrop-blur-md'
          ></animated.div>
        </>
      )}
    </>
  )
}
