// src/lib/components/ui/search/SearchResults.svelte
<script>
	import { createEventDispatcher } from 'svelte';
	import { truncate } from '$lib/utils/truncate';
	import { fly } from 'svelte/transition';

	const dispatch = createEventDispatcher();

	export let searchResults = null;

	function handleDispatchTrack(track) {
		dispatch('addSongToPlaylist', {
			track
		});
	}
</script>

<div class="search-results bg-black/30 p-3 mt-6 rounded-xl relative pt-6">
	<!-- close button-->
	<div
		on:click={() => dispatch('closeSearch')}
		class="close-button bg-white rounded-full p-1 hover:bg-green-500 cursor-pointer text-black absolute right-0 -top-2"
	>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			class="h-5 w-5 text-gray-800"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			stroke-width="2"
		>
			<path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
		</svg>
	</div>
	<!-- display tracks from search -->
	{#if searchResults?.tracks?.items?.length}
		{#each searchResults?.tracks?.items as track, i}
			<div
				in:fly={{ duration: 100, delay: i * 50, x: 30 }}
				class="track track px-4 py-3 hover:bg-green-900 flex gap-3 items-center"
			>
				<div class="track-album-image">
					<img class="track-image" src={track.album.images[0]?.url} alt={track.album.name} />
				</div>
				<div class="track-name">
					{truncate(track.name, 30)}
					<span class="block artist-name">
						{#each track.artists as artist, x}
							<span class={x !== 0 ? 'text-gray-400' : 'text-gray-300'}>
								{x !== 0 ? '/ ' : ''}{truncate(artist.name, 40)}
							</span>
						{/each}
					</span>
				</div>
				<div class="actions flex gap-3 justify-end ml-auto items-center">
					<div on:click={() => handleDispatchTrack(track)}>
						<svg
							xmlns="http://www.w3.org/2000/svg"
							class="h-5 w-5 hover:text-green-500 cursor-pointer"
							fill="none"
							viewBox="0 0 24 24"
							stroke="currentColor"
							stroke-width="2"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"
							/>
						</svg>
					</div>
					<!--<div>add to other playlist</div>-->
				</div>
			</div>
		{/each}
	{:else}
		<div
			class="no-tracks text-white/30 absolute text-center top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 flex flex-wrap justify-center w-full"
		>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				class="h-32 w-32"
				fill="none"
				viewBox="0 0 24 24"
				stroke="currentColor"
				stroke-width="2"
			>
				<path
					stroke-linecap="round"
					stroke-linejoin="round"
					d="M8 16l2.879-2.879m0 0a3 3 0 104.243-4.242 3 3 0 00-4.243 4.242zM21 12a9 9 0 11-18 0 9 9 0 0118 0z"
				/>
			</svg>
			<h3 class="text-3xl font-light">Insert text to search..</h3>
		</div>
	{/if}
	<!-- end display tracks -->
</div>

<style>
	.search-results {
		min-height: 300px;
	}

	.track {
		font-size: 0.8rem;
	}

	.track-image {
		min-width: 30px;
		min-height: 30px;
		max-width: 30px;
		max-height: 30px;
	}

	.artist-name {
		font-size: 0.7rem;
	}
</style>

// src/components/ui/search/SearchResults.tsx
import React, { useEffect, useState } from 'react'
import { useDebounce } from 'src/hooks/useDebounce'
import { useAtom } from 'jotai'
import { truncate } from 'src/utils/truncate'
import { trackAtom, searchAtom, searchTermsAtom } from 'src/store/store'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Track } from 'src/types/spotify'
import { useRouter } from 'next/router'
import { Portal } from 'react-portal'
import Modal from '../modal/Modal'
import Dropdown from '../forms/Dropdown'
import { DropdownEntry } from 'src/types/ui'
import { toast } from 'react-toastify'
import Image from 'next/future/image'

export default function SearchResults() {
  const [search] = useAtom(searchAtom)
  const [searchTerms] = useAtom(searchTermsAtom)
  const debouncedSearchTerms = useDebounce(searchTerms, 500)
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false)
  const [selectedPlaylist, setSelectedPlaylist] = useState<string | null>(null)
  const queryClient = useQueryClient()
  const [track, setTrack] = useAtom(trackAtom)

  const [dropdownEntries, setDropdownEntries] = useState<
    DropdownEntry[] | null
  >(null)

  const router = useRouter()

  function handleClose() {
    setIsModalOpen(false)
  }

  function handleChange(e: React.ChangeEvent<HTMLSelectElement>) {
    setSelectedPlaylist(e.target.value)
  }

  const {
    data: resultsData,
    isLoading,
    isError,
  } = useQuery(
    ['searchSongs', debouncedSearchTerms],
    async () => {
      const res = await fetch(`/api/search?terms=${searchTerms}`)

      return res.json()
    },
    {
      enabled: !!debouncedSearchTerms,
    }
  )

  // add a track or open modal
  // depending on selected playlist or not
  function handleAddTrack(track: any) {
    if (selectedPlaylist) {
      // is playlist - meaning we can open
      addTrack.mutate(track)

      return
    }
    // is not in a playlist so open modal
    if (!isModalOpen) {
      setIsModalOpen(true)
      setTrack(track)
      return
    }
  }

  function handleCloseModalReset() {
    setIsModalOpen(false)
    setSelectedPlaylist(null)
  }

  const { data } = useQuery(['getPlaylists'], async () => {
    const res = await fetch('/api/playlists')

    return res.json()
  })

  useEffect(() => {
    if (!isModalOpen) {
      return
    }

    let toAdd: DropdownEntry[] = []

    for (const playlist of data.items) {
      toAdd.push({
        name: playlist.name,
        value: playlist.id,
      })
    }

    setDropdownEntries(toAdd)
  }, [data, isModalOpen])

  useEffect(() => {
    if (router.pathname.indexOf('/playlist/') > -1) {
      // find which one
      if (!router.query?.id) {
        return
      }

      setSelectedPlaylist(router.query.id.toString())
    } else {
      setSelectedPlaylist(null)
    }
  }, [router, data])

  const addTrack = useMutation(
    async (track: any) => {
      const res = await fetch(
        `/api/addToPlaylist?playlistId=${selectedPlaylist}&trackUri=${track.uri}`
      )
      return res.json()
    },
    {
      onSuccess: (_, variables) => {
        queryClient.invalidateQueries(['getPlaylist'])
        // remove the added track from recommended

        let updatedData = resultsData
        // remove the added track from results
        updatedData.tracks.items = resultsData.tracks.items.filter(
          (f: any) => f.uri !== variables.uri
        )

        queryClient.setQueryData(['searchSongs'], updatedData)

        setTrack(variables)
        // if you got rid of all the searched songs
        // then refetch
        if (resultsData?.tracks?.items?.length === 1) {
          queryClient.invalidateQueries(['searchSongs'])
        }

        toast(`${variables.name} successfully added to the playlist`)

        if (isModalOpen) {
          handleCloseModalReset()
        }
      },
    }
  )

  return (
    <>
      {search && debouncedSearchTerms && (
        <div className='results h-5/6 overflow-y-scroll mt-8'>
          {isLoading && <div className='text-center w-full'>loading...</div>}

          {resultsData && (
            <>
              {resultsData?.tracks?.items?.map((track: Track) => (
                <div
                  key={track.id}
                  className={`track px-4 py-3 hover:bg-green-900 flex gap-3 items-center`}
                >
                  <div className='track-album-image'>
                    <Image
                      width={40}
                      height={40}
                      className='w-8 h-8'
                      src={track.album.images[0]?.url}
                      alt={track.album.name}
                    />
                  </div>
                  <div className='track-name text-sm'>
                    {truncate(track.name, 30)}
                    <span className={`block artist-name text-xs`}>
                      {track.artists.map((artist: any, index: number) => (
                        <span
                          key={artist.id}
                          className={`${
                            index !== 0 ? 'text-gray-400' : 'text-gray-300'
                          }`}
                        >
                          {index !== 0 ? '/ ' : ''}
                          {truncate(artist.name, 40)}
                        </span>
                      ))}
                    </span>
                  </div>
                  <div className='actions flex gap-3 justify-end ml-auto items-center'>
                    <div onClick={() => handleAddTrack(track)}>
                      <svg
                        xmlns='http://www.w3.org/2000/svg'
                        className='h-5 w-5 hover:text-green-500 cursor-pointer'
                        fill='none'
                        viewBox='0 0 24 24'
                        stroke='currentColor'
                        strokeWidth='2'
                      >
                        <path
                          strokeLinecap='round'
                          strokeLinejoin='round'
                          d='M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z'
                        />
                      </svg>
                    </div>
                  </div>
                </div>
              ))}
            </>
          )}
          <Portal>
            <Modal
              modalTitle='Add to which playlist?'
              open={isModalOpen}
              handleClose={handleClose}
            >
              {dropdownEntries?.length && (
                <Dropdown
                  handleChange={handleChange}
                  id='playlist-select'
                  entries={dropdownEntries}
                />
              )}

              <div className='buttons mt-4 flex items-center justify-end gap-3'>
                <button
                  onClick={handleCloseModalReset}
                  className='rounded-full font-bold uppercase bg-gray-500 hover:bg-gray-600 text-white px-3 py-2'
                >
                  Cancel
                </button>
                <button
                  onClick={() => handleAddTrack(track)}
                  className='rounded-full font-bold uppercase bg-green-500 hover:bg-green-600 text-black px-3 py-2'
                >
                  {addTrack.isLoading ? <>Adding...</> : <>Save</>}
                </button>
              </div>
            </Modal>
          </Portal>
        </div>
      )}
    </>
  )
}
