// src/components/ui/forms/Dropdown.tsx
import React from 'react'
import { DropdownEntry } from 'src/types/ui'
import { HiChevronDown } from 'react-icons/hi'

export default function Dropdown({
  id,
  entries,
  label,
  initialOption,
  handleChange,
}: {
  id: string
  entries: DropdownEntry[]
  label?: string
  initialOption?: DropdownEntry
  handleChange: React.ChangeEventHandler
}) {
  return (
    <>
      {label && <label htmlFor={id}>{label}</label>}
      <div className='relative rounded-full w-full bg-gray-100 text-neutral-500 border border-gray-200 focus:outline-2 outline-lime-400'>
        <select
          onChange={(e) => handleChange(e)}
          className='appearance-none px-4 relative py-2 rounded-full w-full bg-gray-100 text-neutral-500 border border-gray-200 focus:outline-2 outline-lime-400'
          id={id}
        >
          {initialOption ? (
            <option value={initialOption.value}>{initialOption.name}</option>
          ) : (
            <option value=''>Please select...</option>
          )}
          {entries.map((entry: DropdownEntry) => (
            <option key={entry.value} value={entry.value}>
              {entry.name}
            </option>
          ))}
        </select>
        <div className='absolute right-3 top-1/2 transform -translate-y-1/2'>
          <HiChevronDown />
        </div>
      </div>
    </>
  )
}

// src/lib/components/ui/forms/Dropdown.svelte
<script>
	export let entries = [];
	export let value = null;
	export let initialOption = null;

	$: if (!value) {
		value = '';
	}
</script>

<div class="dropdown relative">
	<select
		class="appearance-none border rounded-full bg-gray-50 border-gray-200 pl-3 pr-6 py-2"
		bind:value
	>
		{#if !initialOption}
			<option value=""> Please select... </option>
		{/if}

		{#each entries || [] as entry}
			<option value={entry.id}>
				{entry.name}
			</option>
		{/each}
	</select>
	<span
		class="pointer-events-none icon h-6 w-6 absolute right-2 top-2/4 transform -translate-y-2/4 hover:bg-transparent"
	>
		<!-- expand more-->
		<svg
			xmlns="http://www.w3.org/2000/svg"
			class="fill-current h-6 w-6"
			viewBox="0 0 24 24"
			fill="#000000"
			><path d="M0 0h24v24H0z" fill="none" /><path
				d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"
			/></svg
		>
	</span>
</div>
