// src/components/widgets/playlist-wizard/PlaylistWizard.tsx
import React, { useEffect, useState } from 'react'
import Head from 'next/head'

import type { Purpose } from './types'
import { playlistPurposes } from './purposes'
import { useMutation, useQuery } from '@tanstack/react-query'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/router'
import { useAutoAnimate } from '@formkit/auto-animate/react'
import { useSpring, animated } from 'react-spring'

import {
  uniqueNamesGenerator,
  adjectives,
  colors,
  animals,
} from 'unique-names-generator'
import Workout from 'src/components/ui/icons/Workout'
import Travel from 'src/components/ui/icons/Travel'
import Chilling from 'src/components/ui/icons/Chilling'
import Party from 'src/components/ui/icons/Party'
import Gaming from 'src/components/ui/icons/Gaming'
import Anything from 'src/components/ui/icons/Anything'
export default function PlaylistWizard() {
  const [playlistName, setplaylistName] = useState<string>('')
  const [selectedPurpose, setSelectedPurpose] = useState<Purpose | null>(null)
  const [selectedGenres, setSelectedGenres] = useState<string[]>([])
  const [pickGenres, setPickGenres] = useState<boolean>(false)
  const [trackNumber, setTrackNumber] = useState<number | null>(null)

  const [show, setShow] = useState<boolean>(false)

  const [playlistState, setPlaylistState] = useState<string | null>('')
  const [parent] = useAutoAnimate<HTMLDivElement>()

  const genreStyles = useSpring({
    opacity: pickGenres ? 1 : 0,
    y: pickGenres ? 0 : 400,
  })

  const trackNumberStyles = useSpring({
    opacity: selectedPurpose ? 1 : 0,
  })

  const { data: session } = useSession()

  const router = useRouter()

  useEffect(() => {
    const randomName = uniqueNamesGenerator({
      dictionaries: [adjectives, colors, animals],
      separator: ' ',
      length: 3,
    })
    setplaylistName(randomName)
  }, [])

  useEffect(() => {
    setShow(true)
  }, [show])

  const trackNumbers = [5, 10, 20, 30, 40, 60, 80, 100]

  const { data: genres } = useQuery(
    ['getGenres', selectedPurpose],
    async () => {
      const res = await fetch(`/api/genres`)

      return res.json()
    }
  )

  function handleSelectedGenre(genre: string) {
    if (selectedGenres.find((f: string) => f === genre)) {
      const updatedGenre = selectedGenres.filter((g: string) => g !== genre)
      setSelectedGenres(updatedGenre)

      return
    }

    if (selectedGenres.length === 3) {
      return
    }

    const updatedGenres = [...selectedGenres, genre]
    setSelectedGenres(updatedGenres)
  }

  function handleTrackNumber(number: number) {
    if (number === trackNumber) {
      setTrackNumber(null)

      return
    }

    setTrackNumber(number)
  }

  const createPlaylist = useMutation(
    async () => {
      setPlaylistState('loading')

      const playlist_name = `playlist_name=${playlistName}`
      const params = new URLSearchParams(playlist_name)
      const user_id = session?.token?.id as string
      const seeds: any = selectedPurpose?.seeds

      let seedString: string | null = null
      let seedGenres: string | null = null

      if (user_id) {
        params.set('user_id', user_id)
      }

      if (trackNumber) {
        params.set('limit', trackNumber.toString())
      }

      if (seeds) {
        seedString =
          '&' +
          Object.keys(seeds)
            .map((key) => key + '=' + seeds[key])
            .join('&')
            .toString()
      }

      if (selectedGenres?.length) {
        seedGenres = '&seed_genres=' + selectedGenres.join(',')
      }

      const string = [seedString, seedGenres].join('&')

      return await fetch(`/api/create-playlist?${params}` + string)
    },
    {
      onSuccess: async (data: any) => {
        const playlist = await data.json()
        setPlaylistState('done')

        if (playlist) {
          router.push(`/playlist/${playlist.id}`)
        }
      },
      onError: async () => {
        setPlaylistState('error')
      },
    }
  )

  return (
    <>
      <Head>
        <title>Playlistr | Create New Playlist</title>
      </Head>
      <div ref={parent}>
        {show && (
          <div className='transition-all bg-neutral-800/80 p-6 rounded-3xl mt-2'>
            <div className='playlist-name'>
              <h4 className='mb-2 tracking-tighter text-xs font-extrabold uppercase'>
                Playlist name
              </h4>
              <input
                className='bg-neutral-600/80 w-full md:w-80 text-xl rounded-2xl px-4 py-2 focus:outline-1 outline-green-500'
                type='text'
                value={playlistName}
                autoFocus
                onChange={(e) => setplaylistName(e.target.value)}
              ></input>
            </div>
            <div className='wizard-form w-full'>
              <div className='title text-center mt-4 mb-8 text-gray-300 text-2xl'>
                <h4>What{`'`}s the purpose of the playlist?</h4>
              </div>
              <div className='playlist-purposes mb-8 mt-4 flex flex-wrap gap-3 justify-center'>
                {playlistPurposes.map((purpose) => (
                  <div
                    onClick={() => setSelectedPurpose(purpose)}
                    key={purpose.id}
                    className={`${
                      selectedPurpose?.id === purpose.id
                        ? 'bg-green-600/80 hover:bg-green-800/80'
                        : 'bg-neutral-500/20 hover:bg-neutral-600/60'
                    } playlist-purpose-item cursor-pointer  rounded-md p-4 w-36 text-center text-sm uppercase font-semibold`}
                  >
                    <div className='purpose-icon text-4xl mb-2'>
                      {purpose.name === 'Working out' && (
                        <Workout
                          isSelected={selectedPurpose?.id === purpose.id}
                        />
                      )}
                      {purpose.name === 'Traveling' && (
                        <Travel
                          isSelected={selectedPurpose?.id === purpose.id}
                        />
                      )}
                      {purpose.name === 'Chilling' && (
                        <Chilling
                          isSelected={selectedPurpose?.id === purpose.id}
                        />
                      )}
                      {purpose.name === 'Partying' && (
                        <Party
                          isSelected={selectedPurpose?.id === purpose.id}
                        />
                      )}
                      {purpose.name === 'Gaming' && (
                        <Gaming
                          isSelected={selectedPurpose?.id === purpose.id}
                        />
                      )}
                      {purpose.name === 'Anything' && (
                        <Anything
                          isSelected={selectedPurpose?.id === purpose.id}
                        />
                      )}
                    </div>
                    <div className='purpose-name'>{purpose.name}</div>
                  </div>
                ))}
              </div>

              {selectedPurpose && (
                <>
                  <animated.div
                    style={trackNumberStyles}
                    className='select-track-number text-center mt-4 mb-4 text-gray-300 text-2xl'
                  >
                    <h4>How many tracks would you like to add?</h4>
                    <div className='track-numbers mt-4 flex gap-3 justify-center flex-wrap'>
                      {trackNumbers.map((number: number) => (
                        <div
                          onClick={() => handleTrackNumber(number)}
                          key={number}
                          className={` ${
                            trackNumber === number
                              ? 'bg-green-600/80 hover:bg-green-800/80'
                              : 'bg-neutral-500/20 hover:bg-neutral-600/80'
                          }  cursor-pointer w-20 rounded-md px-4 py-2 text-sm font-extrabold`}
                        >
                          {number}
                        </div>
                      ))}
                    </div>
                  </animated.div>

                  <div className='select-genre text-center relative'>
                    {genres && pickGenres && (
                      <animated.div style={genreStyles}>
                        <div className='info-text sticky top-0 backdrop-blur-lg py-4'>
                          <h4 className='text-2xl text-gray-200'>
                            Select up to 3 genres (or none if you don{`'`}t
                            care)
                          </h4>
                          <h5 className='text-gray-400 text-sm'>
                            if you don{`'`}t select a genre we will guess tracks
                            based on your top artists
                          </h5>
                        </div>
                        <div className='genres my-4'>
                          <div className='flex gap-3 relative justify-center flex-column flex-wrap w-full'>
                            {genres?.map((genre: string) => (
                              <div
                                key={genre}
                                onClick={() => handleSelectedGenre(genre)}
                                className={`
                    ${
                      selectedGenres.filter((f: string) => f === genre).length
                        ? 'selected'
                        : 'border-transparent'
                    } border playlist-purpose-item cursor-pointer bg-neutral-600/30 hover:bg-green-600 border-white rounded-md p-2 text-center text-xs uppercase font-semibold`}
                              >
                                {genre}
                              </div>
                            ))}
                          </div>
                        </div>
                      </animated.div>
                    )}
                    <div className='pre-selection mt-8'>
                      {!pickGenres && (
                        <>
                          <button
                            onClick={() => setPickGenres(true)}
                            className='mx-auto block create-playlist bg-neutral-600 hover:bg-green-800 cursor-pointer uppercase text-sm font-bold rounded-full justify-center px-9 py-2 w-max text-center'
                          >
                            select up to 3 Genres
                          </button>
                          <div className='or-text py-2 my-0 text-xs font-extrabold tracking-tighter'>
                            OR
                          </div>
                        </>
                      )}
                      <button
                        onClick={() => createPlaylist.mutate()}
                        className={`
                    ${
                      playlistState === 'loading'
                        ? 'bg-neutral-600 hover:bg-neutral-600 pointer-events-none'
                        : 'bg-green-600'
                    }
                    ${
                      playlistState === 'error'
                        ? 'bg-red-300 hover:bg-red-400 pointer-events-none'
                        : 'bg-green-600'
                    }
                  mx-auto block create-playlist  hover:bg-green-700 cursor-pointer uppercase text-sm font-bold rounded-full justify-center px-9 py-2 w-max text-center`}
                      >
                        {playlistState === 'loading' ? (
                          <>Loading...</>
                        ) : (
                          <>Create Playlist</>
                        )}
                      </button>
                    </div>
                  </div>
                </>
              )}
            </div>
          </div>
        )}
      </div>
    </>
  )
}

// src/lib/components/widgets/PlaylistWizard.svelte
<script>
	import { uniqueNamesGenerator, adjectives, colors, animals } from 'unique-names-generator';
	import { user } from '$lib/stores/user';
	import { fly } from 'svelte/transition';
	import ActionButton from '../ui/buttons/ActionButton.svelte';
	import EditableText from '../ui/editable-inputs/EditableText.svelte';
	import { onMount, getContext } from 'svelte';
	import { notification } from '$lib/stores/notification';
	import { goto } from '$app/navigation';

	let session = getContext('session');
	let availableGenres = null;
	let selectedGenres = [];

	onMount(async () => {
		availableGenres = await getAvailableGenres();
	});

	async function getAvailableGenres() {
		try {
			const data = await fetch(`https://api.spotify.com/v1/recommendations/available-genre-seeds`, {
				method: 'GET',
				headers: {
					Authorization: `Bearer ${session.access_token}`
				}
			});
			return await data.json();
		} catch (error) {
			console.error(error);
		}
	}

	const playlistPurposes = [
		{
			id: 1,
			name: 'Working out',
			icon: `💪`,
			seeds: {
				min_energy: 0.6,
				// min_tempo: 160,
				min_danceability: 0.6
			}
		},
		{
			id: 2,
			name: 'Traveling',
			icon: `🏝`,
			seeds: {
				max_energy: 0.6,
				max_tempo: 160
			}
		},
		{
			id: 3,
			name: 'Chilling',
			icon: `😌`,
			seeds: {
				max_energy: 0.6,
				max_tempo: 150
			}
		},
		{
			id: 4,
			name: 'Partying',
			icon: `🎉`,
			seeds: {
				min_danceability: 0.7,
				max_tempo: 160
			}
		},
		{
			id: 5,
			name: 'Gaming',
			icon: `🎮`,
			seeds: {
				min_energy: 0.3,
				min_popularity: 50
			}
		},
		{
			id: 6,
			name: 'Anything',
			icon: `🙌`
		}
	];

	const amountOfTracks = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100];

	let selectedPurpose = null;
	let selectedAmount = null;
	let playlistName = null;

	const randomName = uniqueNamesGenerator({
		dictionaries: [adjectives, colors, animals],
		separator: ' ',
		length: 3
	});

	async function generatePlaylist() {
		// generate playlist here
		if (!selectedPurpose || !selectedAmount || !playlistName || !$user?.id) {
			// TODO handle errors
			return;
		}

		const seeds = selectedPurpose.seeds;
		const genres = selectedPurpose.seed_genres;
		const name = {
			name: playlistName
		};
		const amount = selectedAmount;

		const seedString = Object.keys(seeds)
			.map((key) => key + '=' + Number(seeds[key]))
			.join('&');

		const queryString = seedString + '&limit=' + amount;

		// first create playlist then add items to them
		let created = null;
		let seed_artists = null;

		try {
			const data = await fetch(`https://api.spotify.com/v1/users/${$user.id}/playlists`, {
				method: 'POST',
				headers: {
					Authorization: `Bearer ${session.access_token}`
				},
				body: JSON.stringify(name)
			});
			created = await data.json();
		} catch (error) {
			console.error(error);
		}

		if (created && !selectedGenres.length) {
			// find artist seed
			try {
				const offset = Math.floor(Math.random() * 10);
				const artistSeedData = await fetch(
					`https://api.spotify.com/v1/me/top/artists?limit=5&offset=${offset}`,
					{
						method: 'GET',
						headers: {
							Authorization: `Bearer ${session.access_token}`
						}
					}
				);
				const artistsData = await artistSeedData.json();
				seed_artists = artistsData?.items.map(function (artist) {
					return artist['id'];
				});
			} catch (error) {
				console.error(error);
			}
		}

		const playlistId = created.id;
		let recommendations = null;
		// add tracks to playlist
		try {
			if (genres?.length) {
				selectedGenres.push(genres);
			}

			const seeds_string = seed_artists
				? 'seed_artists=' + seed_artists.join(',')
				: 'seed_genres=' + selectedGenres.join(',');

			const recommendationsData = await fetch(
				`https://api.spotify.com/v1/recommendations?${seeds_string}&${queryString}`,
				{
					method: 'GET',
					headers: {
						Authorization: `Bearer ${session.access_token}`
					}
				}
			);

			recommendations = await recommendationsData.json();
		} catch (error) {
			console.error(error);
		}

		const tracks = recommendations?.tracks.map((track) => track.uri);

		if (tracks) {
			try {
				const addToPlaylist = await fetch(
					`https://api.spotify.com/v1/playlists/${playlistId}/tracks?uris=${tracks.join(',')}`,
					{
						method: 'POST',
						headers: {
							Authorization: `Bearer ${session.access_token}`
						}
					}
				);
				if (!addToPlaylist.ok) {
					console.error('error adding to playlist');
					$notification = {
						type: 'error',
						message: `Error adding to playlist`
					};
				} else {
					$notification = {
						type: 'success',
						message: `Playlist ${created.name} created!`
					};
					goto('/playlist/' + created.id);
				}
			} catch (error) {
				console.error(rrror);
			}
		}
	}

	function handleGenres(genre) {
		if (selectedGenres.includes(genre)) {
			selectedGenres = selectedGenres.filter((g) => g !== genre);
		} else {
			selectedGenres.push(genre);
		}
		selectedGenres = selectedGenres;
	}

	// function resetSelections () {
	//   selectedPurpose = null;
	//   selectedAmount = null;
	//   playlistName = null;
	//   selectedGenres = [];
	// }
</script>

<div class="playlist-wizard mt-8 text-center rounded-2xl p-8">
	<div class="playlist-name text-left mb-4">
		<h3 class="text-xs uppercase font-semibold mb-1">New Playlist</h3>
		<EditableText
			bind:value={playlistName}
			extraClass="text-2xl"
			editOnMount
			initialValue={randomName}
		/>
	</div>
	<h2 class="text-xl font-light text-gray-300 mb-4">What's the purpose of the playlist?</h2>
	<div class="playlist-purpose justify-center flex flex-wrap gap-3 mb-4">
		{#each playlistPurposes as purpose}
			<div
				on:click={() => {
					selectedPurpose = purpose;
				}}
				class="{selectedPurpose?.id === purpose.id
					? 'selected'
					: 'border-transparent'} border playlist-purpose-item cursor-pointer hover:bg-green-600 rounded-md p-4 w-36 text-center text-sm uppercase font-semibold"
			>
				<div class="purpose-icon text-4xl mb-2">
					{purpose.icon}
				</div>
				<div class="purpose-name">
					{purpose.name}
				</div>
			</div>
		{/each}
	</div>
	{#if selectedPurpose}
		<div class="select-genres mx-auto mb-4">
			<h2 class="text-xl font-light text-gray-300 mb-4">
				Select up to 3 genres (or none if you don't care)
				<small class="block text-xs">
					if you don't select a genre we'll guess tracks based on your top artists
				</small>
			</h2>
			<div class="genres flex gap-3 flex-wrap justify-center">
				{#each availableGenres.genres || [] as genre, i}
					<div
						in:fly={{ duration: 80, delay: i * 10, y: -10 }}
						on:click={() => handleGenres(genre)}
						class="{selectedGenres.filter((f) => f === genre).length
							? 'selected'
							: 'border-transparent'} border playlist-purpose-item cursor-pointer hover:bg-green-600 border-white rounded-md p-2 w-max text-center text-sm uppercase font-semibold"
					>
						{genre}
					</div>
				{/each}
			</div>
		</div>
		<div class="number-of-tracks mx-auto mb-8">
			<h2 class="text-xl font-light text-gray-300 mb-4">
				How many tracks would you like to add? (up to 100)
			</h2>
			<div class="predefined-amount gap-3 flex flex-wrap justify-center mb-4">
				{#each amountOfTracks as amount}
					<div
						on:click={() => {
							selectedAmount = amount;
						}}
						class="{selectedAmount === amount
							? 'selected'
							: 'border-transparent'} border playlist-purpose-item cursor-pointer hover:bg-green-600 rounded-md p-4 w-max text-center text-sm uppercase font-semibold"
					>
						{amount}
					</div>
				{/each}
			</div>
			<!-- <InputNumber extraClass="mx-auto" widthClass="w-max" min="1" max="100" value="20" /> -->
		</div>
	{/if}

	{#if selectedPurpose && selectedAmount}
		<div class="finalise-playlist mt-4">
			<ActionButton green={true} on:click={generatePlaylist}>Generate playlist</ActionButton>
		</div>
	{/if}
</div>

<style>
	.playlist-wizard {
		background: rgba(0, 0, 0, 0.4);
		backdrop-filter: blur(10px);
	}
	.playlist-purpose-item {
		transition: 0.3s ease;
		font-size: 0.75rem;
		background: rgba(0, 0, 0, 0.2);
		border: 1px solid rgba(255, 255, 255, 0.3);
	}

	.playlist-purpose-item:hover {
		background: rgba(0, 0, 0, 0.8);
		border: 1px solid rgba(255, 255, 255, 0.3);
	}

	.selected {
		background: green;
	}
</style>
